// 共享层：全局常量定义
// 此文件被前端（client/）通过 @shared/constants 引用
// 后端（server/）不引用此文件，如有需要在 server/src/core/errors.js 中维护等价定义
//
// 注意：保持纯常量，不引入运行时依赖，确保可被前后端安全引用

// ========== 错误码 ==========
// 前缀 CLASSINTRA_*，与 Ditto 的 DITTO_* 共存
// 格式：CLASSINTRA_<域>_<具体错误>
var ERROR_CODES = {
  // 存储 / 持久化
  STORAGE_UNAVAILABLE: 'CLASSINTRA_STORAGE_UNAVAILABLE',
  STORAGE_QUOTA_EXCEEDED: 'CLASSINTRA_STORAGE_QUOTA_EXCEEDED',
  STORAGE_CORRUPTED: 'CLASSINTRA_STORAGE_CORRUPTED',

  // 应用系统
  APP_NOT_FOUND: 'CLASSINTRA_APP_NOT_FOUND',
  APP_DISABLED: 'CLASSINTRA_APP_DISABLED',
  APP_LOAD_FAILED: 'CLASSINTRA_APP_LOAD_FAILED',

  // 主题系统
  THEME_NOT_FOUND: 'CLASSINTRA_THEME_NOT_FOUND',
  THEME_INVALID: 'CLASSINTRA_THEME_INVALID',

  // 集成系统（阶段 4 用，本期预留）
  INTEGRATION_UNAUTHORIZED: 'CLASSINTRA_INTEGRATION_UNAUTHORIZED',
  INTEGRATION_FORBIDDEN: 'CLASSINTRA_INTEGRATION_FORBIDDEN',
  INTEGRATION_TIMEOUT: 'CLASSINTRA_INTEGRATION_TIMEOUT',
  INTEGRATION_INVALID_ENVELOPE: 'CLASSINTRA_INTEGRATION_INVALID_ENVELOPE',
  INTEGRATION_UNKNOWN_CHANNEL: 'CLASSINTRA_INTEGRATION_UNKNOWN_CHANNEL',
  INTEGRATION_NO_TARGET: 'CLASSINTRA_INTEGRATION_NO_TARGET',
  INTEGRATION_ERROR: 'CLASSINTRA_INTEGRATION_ERROR',
  INTEGRATION_CLOSED: 'CLASSINTRA_INTEGRATION_CLOSED',
  INTEGRATION_SIGNATURE_INVALID: 'CLASSINTRA_INTEGRATION_SIGNATURE_INVALID',
  INTEGRATION_TOKEN_EXPIRED: 'CLASSINTRA_INTEGRATION_TOKEN_EXPIRED',

  // 服务编排
  SERVICE_NOT_FOUND: 'CLASSINTRA_SERVICE_NOT_FOUND',
  SERVICE_UNAVAILABLE: 'CLASSINTRA_SERVICE_UNAVAILABLE',
  SERVICE_ALREADY_REGISTERED: 'CLASSINTRA_SERVICE_ALREADY_REGISTERED',

  // 通用错误
  PERMISSION_DENIED: 'CLASSINTRA_PERMISSION_DENIED',
  NETWORK_ERROR: 'CLASSINTRA_NETWORK_ERROR',
  DB_ERROR: 'CLASSINTRA_DB_ERROR',
  VALIDATION_ERROR: 'CLASSINTRA_VALIDATION_ERROR',
  NOT_FOUND: 'CLASSINTRA_NOT_FOUND',
  CONFLICT: 'CLASSINTRA_CONFLICT',
  RATE_LIMITED: 'CLASSINTRA_RATE_LIMITED',
  INTERNAL_ERROR: 'CLASSINTRA_INTERNAL_ERROR',
  UNKNOWN: 'CLASSINTRA_UNKNOWN'
};

// ========== 事件名 ==========
// EventBus（client/src/core/event-bus.js）使用的全局事件名
// 局部事件可由各模块自定义，不在此处声明
var EVENT_NAMES = {
  THEME_CHANGED: 'theme:changed',
  THEME_MOTION_TOGGLED: 'theme:motion-toggled',
  APP_LAUNCHED: 'app:launched',
  APP_CLOSED: 'app:closed',
  USER_SIGNED_IN: 'user:signed-in',
  USER_SIGNED_OUT: 'user:signed-out',
  INTEGRATION_HANDSHAKE: 'integration:handshake',
  INTEGRATION_EVENT: 'integration:event',
  INTEGRATION_DISCONNECTED: 'integration:disconnected'
};

// ========== Storage 前缀 ==========
// PersistenceStore（client/src/core/persistence-store.js）使用的 localStorage key 前缀
// 避免与其他应用的 localStorage key 冲突
var STORAGE_PREFIX = 'classintra:';

// ========== 集成协议常量（阶段 4 用，本期预留） ==========
var INTEGRATION_MSG_TYPE = 'classintra-integration';
var INTEGRATION_PROTOCOL_VERSION = '1.0';
var INTEGRATION_DEFAULT_TIMEOUT_MS = 10000;
var INTEGRATION_DEFAULT_TOKEN_TTL_DAYS = 30;

export {
  ERROR_CODES,
  EVENT_NAMES,
  STORAGE_PREFIX,
  INTEGRATION_MSG_TYPE,
  INTEGRATION_PROTOCOL_VERSION,
  INTEGRATION_DEFAULT_TIMEOUT_MS,
  INTEGRATION_DEFAULT_TOKEN_TTL_DAYS
};
